import Head from 'next/head'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Post from '../components/Post'
import styles from '../styles/Home.module.css'

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Qt Coder's blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="posts">
        {posts.map((post, index) => (
          <Post post={post} key={index}/>
        ))}
      </div>

      <div className={styles.footer}>
        <a href='https://github.com/qt-coder' target='_empty'>Github</a>
      </div>
    </div>
  )
}

export async function getStaticProps() {

  const files = fs.readdirSync(path.join('posts'))

  const posts = files.map((filename) => {
    const slug = filename.replace('.md', '')

    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')

    const { data: frontmatter } = matter(markdownWithMeta)

    return {
      slug,
      frontmatter
    }
  })

  return {
    props: {
      posts
    }
  }
}